use std::{env, fs, path::PathBuf};

const TRAY_ICON_SIZE: u32 = 40;
const TRAY_ICON_OVERSAMPLE_SCALE: u32 = 4;
const FLUENT_ICON_VISUAL_SCALE: f32 = 1.26;
const FLUENT_FILL_COLOR: &str = "#212121";
const FLUENT_BATTERY_SVGS: [&str; 11] = [
    "ic_fluent_battery_0_24_regular.svg",
    "ic_fluent_battery_1_24_regular.svg",
    "ic_fluent_battery_2_24_regular.svg",
    "ic_fluent_battery_3_24_regular.svg",
    "ic_fluent_battery_4_24_regular.svg",
    "ic_fluent_battery_5_24_regular.svg",
    "ic_fluent_battery_6_24_regular.svg",
    "ic_fluent_battery_7_24_regular.svg",
    "ic_fluent_battery_8_24_regular.svg",
    "ic_fluent_battery_9_24_regular.svg",
    "ic_fluent_battery_10_24_regular.svg",
];
const COLOR_VARIANTS: [(&str, (u8, u8, u8)); 3] = [
    ("LOW", (196, 43, 28)),
    ("MEDIUM", (202, 80, 16)),
    ("NORMAL", (16, 124, 16)),
];

fn main() {
    generate_fluent_battery_icons();
    tauri_build::build()
}

fn generate_fluent_battery_icons() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let asset_dir = manifest_dir.join("assets").join("fluent-battery");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let output_path = out_dir.join("fluent_battery_icons.rs");

    println!("cargo:rerun-if-changed={}", asset_dir.display());

    let mut output = String::new();
    output.push_str("// @generated by build.rs\n");
    output.push_str(&format!("pub const TRAY_ICON_SIZE: u32 = {TRAY_ICON_SIZE};\n"));
    output.push_str("#[allow(dead_code)]\n");
    output.push_str(&format!(
        "pub const TRAY_ICON_OVERSAMPLE_SCALE: u32 = {TRAY_ICON_OVERSAMPLE_SCALE};\n"
    ));
    output.push_str("pub const COLOR_LOW: usize = 0;\n");
    output.push_str("pub const COLOR_MEDIUM: usize = 1;\n");
    output.push_str("pub const COLOR_NORMAL: usize = 2;\n\n");

    let mut arms = Vec::new();
    for (asset_index, file_name) in FLUENT_BATTERY_SVGS.iter().enumerate() {
        let path = asset_dir.join(file_name);
        println!("cargo:rerun-if-changed={}", path.display());
        let svg = fs::read_to_string(&path).unwrap_or_else(|error| {
            panic!("failed to read Fluent battery asset {}: {error}", path.display())
        });

        for (color_index, (label, color)) in COLOR_VARIANTS.iter().enumerate() {
            let name = format!("BATTERY_{asset_index}_{label}");
            let rgba = render_svg(&svg, *color);
            output.push_str(&format!("const {name}: &[u8] = &{rgba:?};\n"));
            arms.push(format!("        ({asset_index}, {color_index}) => Some({name}),\n"));
        }
    }

    output.push_str("\npub fn fluent_battery_icon_rgba(asset_index: usize, color_index: usize) -> Option<&'static [u8]> {\n");
    output.push_str("    match (asset_index, color_index) {\n");
    for arm in arms {
        output.push_str(&arm);
    }
    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n");

    fs::write(&output_path, output).unwrap_or_else(|error| {
        panic!(
            "failed to write generated Fluent battery icons {}: {error}",
            output_path.display()
        )
    });
}

fn render_svg(svg: &str, (red, green, blue): (u8, u8, u8)) -> Vec<u8> {
    use resvg::{tiny_skia, usvg};

    let svg = svg.replace(FLUENT_FILL_COLOR, &format!("#{red:02X}{green:02X}{blue:02X}"));
    let tree = usvg::Tree::from_str(&svg, &usvg::Options::default())
        .expect("failed to parse Fluent battery SVG");
    let source_size = TRAY_ICON_SIZE * TRAY_ICON_OVERSAMPLE_SCALE;
    let mut pixmap =
        tiny_skia::Pixmap::new(source_size, source_size).expect("failed to allocate pixmap");
    let scale_x = source_size as f32 / tree.size().width() * FLUENT_ICON_VISUAL_SCALE;
    let scale_y = source_size as f32 / tree.size().height() * FLUENT_ICON_VISUAL_SCALE;
    let translate_x = (source_size as f32 - tree.size().width() * scale_x) / 2.0;
    let translate_y = (source_size as f32 - tree.size().height() * scale_y) / 2.0;

    resvg::render(
        &tree,
        tiny_skia::Transform::from_translate(translate_x, translate_y)
            .pre_scale(scale_x, scale_y),
        &mut pixmap.as_mut(),
    );

    let downsampled = downsample_rgba_box(
        pixmap.data(),
        source_size,
        source_size,
        TRAY_ICON_OVERSAMPLE_SCALE,
    );
    unpremultiply_rgba(&downsampled)
}

fn downsample_rgba_box(
    pixels: &[u8],
    source_width: u32,
    source_height: u32,
    factor: u32,
) -> Vec<u8> {
    assert!(factor > 0, "downsample factor must be non-zero");
    assert_eq!(source_width % factor, 0, "source width must divide evenly");
    assert_eq!(
        source_height % factor,
        0,
        "source height must divide evenly"
    );
    assert_eq!(
        pixels.len(),
        (source_width * source_height * 4) as usize,
        "source pixel buffer must match dimensions"
    );

    let target_width = source_width / factor;
    let target_height = source_height / factor;
    let sample_count = factor * factor;
    let mut output = Vec::with_capacity((target_width * target_height * 4) as usize);

    for target_y in 0..target_height {
        for target_x in 0..target_width {
            let mut sums = [0u32; 4];

            for sample_y in 0..factor {
                for sample_x in 0..factor {
                    let source_x = target_x * factor + sample_x;
                    let source_y = target_y * factor + sample_y;
                    let source_index = ((source_y * source_width + source_x) * 4) as usize;

                    for channel in 0..4 {
                        sums[channel] += pixels[source_index + channel] as u32;
                    }
                }
            }

            for sum in sums {
                output.push(((sum + sample_count / 2) / sample_count).min(255) as u8);
            }
        }
    }

    output
}

fn unpremultiply_rgba(pixels: &[u8]) -> Vec<u8> {
    let mut output = Vec::with_capacity(pixels.len());

    for pixel in pixels.chunks_exact(4) {
        let alpha = pixel[3];
        if alpha == 0 || alpha == 255 {
            output.extend_from_slice(pixel);
        } else {
            output.push(unpremultiply_channel(pixel[0], alpha));
            output.push(unpremultiply_channel(pixel[1], alpha));
            output.push(unpremultiply_channel(pixel[2], alpha));
            output.push(alpha);
        }
    }

    output
}

fn unpremultiply_channel(channel: u8, alpha: u8) -> u8 {
    (((channel as u16 * 255) + (alpha as u16 / 2)) / alpha as u16).min(255) as u8
}
