use std::{env, fs, path::PathBuf};

const TRAY_ICON_SIZE: u32 = 40;
const FLUENT_FILL_COLOR: &str = "#212121";
const FLUENT_BATTERY_SVGS: [&str; 11] = [
    "ic_fluent_battery_0_24_regular.svg",
    "ic_fluent_battery_1_24_regular.svg",
    "ic_fluent_battery_2_24_regular.svg",
    "ic_fluent_battery_3_24_regular.svg",
    "ic_fluent_battery_4_24_regular.svg",
    "ic_fluent_battery_5_24_regular.svg",
    "ic_fluent_battery_6_24_regular.svg",
    "ic_fluent_battery_7_24_regular.svg",
    "ic_fluent_battery_8_24_regular.svg",
    "ic_fluent_battery_9_24_regular.svg",
    "ic_fluent_battery_10_24_regular.svg",
];
const COLOR_VARIANTS: [(&str, (u8, u8, u8)); 3] = [
    ("LOW", (196, 43, 28)),
    ("MEDIUM", (202, 80, 16)),
    ("NORMAL", (16, 124, 16)),
];

fn main() {
    generate_fluent_battery_icons();
    tauri_build::build()
}

fn generate_fluent_battery_icons() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let asset_dir = manifest_dir.join("assets").join("fluent-battery");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let output_path = out_dir.join("fluent_battery_icons.rs");

    println!("cargo:rerun-if-changed={}", asset_dir.display());

    let mut output = String::new();
    output.push_str("// @generated by build.rs\n");
    output.push_str(&format!("pub const TRAY_ICON_SIZE: u32 = {TRAY_ICON_SIZE};\n"));
    output.push_str("pub const COLOR_LOW: usize = 0;\n");
    output.push_str("pub const COLOR_MEDIUM: usize = 1;\n");
    output.push_str("pub const COLOR_NORMAL: usize = 2;\n\n");

    let mut arms = Vec::new();
    for (asset_index, file_name) in FLUENT_BATTERY_SVGS.iter().enumerate() {
        let path = asset_dir.join(file_name);
        println!("cargo:rerun-if-changed={}", path.display());
        let svg = fs::read_to_string(&path).unwrap_or_else(|error| {
            panic!("failed to read Fluent battery asset {}: {error}", path.display())
        });

        for (color_index, (label, color)) in COLOR_VARIANTS.iter().enumerate() {
            let name = format!("BATTERY_{asset_index}_{label}");
            let rgba = render_svg(&svg, *color);
            output.push_str(&format!("const {name}: &[u8] = &{rgba:?};\n"));
            arms.push(format!("        ({asset_index}, {color_index}) => Some({name}),\n"));
        }
    }

    output.push_str("\npub fn fluent_battery_icon_rgba(asset_index: usize, color_index: usize) -> Option<&'static [u8]> {\n");
    output.push_str("    match (asset_index, color_index) {\n");
    for arm in arms {
        output.push_str(&arm);
    }
    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n");

    fs::write(&output_path, output).unwrap_or_else(|error| {
        panic!(
            "failed to write generated Fluent battery icons {}: {error}",
            output_path.display()
        )
    });
}

fn render_svg(svg: &str, (red, green, blue): (u8, u8, u8)) -> Vec<u8> {
    use resvg::{tiny_skia, usvg};

    let svg = svg.replace(FLUENT_FILL_COLOR, &format!("#{red:02X}{green:02X}{blue:02X}"));
    let tree = usvg::Tree::from_str(&svg, &usvg::Options::default())
        .expect("failed to parse Fluent battery SVG");
    let mut pixmap =
        tiny_skia::Pixmap::new(TRAY_ICON_SIZE, TRAY_ICON_SIZE).expect("failed to allocate pixmap");
    let scale_x = TRAY_ICON_SIZE as f32 / tree.size().width();
    let scale_y = TRAY_ICON_SIZE as f32 / tree.size().height();

    resvg::render(
        &tree,
        tiny_skia::Transform::from_scale(scale_x, scale_y),
        &mut pixmap.as_mut(),
    );

    unpremultiply_rgba(pixmap.data())
}

fn unpremultiply_rgba(pixels: &[u8]) -> Vec<u8> {
    let mut output = Vec::with_capacity(pixels.len());

    for pixel in pixels.chunks_exact(4) {
        let alpha = pixel[3];
        if alpha == 0 || alpha == 255 {
            output.extend_from_slice(pixel);
        } else {
            output.push(unpremultiply_channel(pixel[0], alpha));
            output.push(unpremultiply_channel(pixel[1], alpha));
            output.push(unpremultiply_channel(pixel[2], alpha));
            output.push(alpha);
        }
    }

    output
}

fn unpremultiply_channel(channel: u8, alpha: u8) -> u8 {
    (((channel as u16 * 255) + (alpha as u16 / 2)) / alpha as u16).min(255) as u8
}
