name: build

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore .\blue_battery\blue_battery.csproj

      - name: Build x64 Debug
        run: dotnet build .\blue_battery\blue_battery.csproj -c Debug -p:Platform=x64 --no-restore
